### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by kiwijam** [dcwatson/deflate#1]
I managed to build deflate under Windows with MSVC. I'm not an Python extensions expert so I'll just leave some pointers in case you decide to add official Windows support.

I had to make the following changes:

setup.py:
```
result = subprocess.run(["nmake", "/f", "Makefile.msc", "/a"], cwd=libdeflate_dir)
...
"deflate", sources=["deflate.c"], extra_objects=["libdeflate/libdeflatestatic.lib"]
```

Furthermore, MSVC's compiler breaks on:

```deflate.c(72): error C2036: 'void *': unknown size```

I'm not sure what the correct fix is, but I changed L72 to

```bytes = (uint8_t *)(data.buf) + (data.len - 4);```

to get it to compile.

**Comment by dcwatson** [comment]
Thanks for the tips! I'll dust off my Windows machine soon and add proper support. I'd also like to use GitHub Actions to build binary wheels at some point, but baby steps.

**Comment by dcwatson** [comment]
A new version (with pre-built wheels) will be published shortly.
