### ISSUE TITLE
add deflate.crc32 api?

### ISSUE THREAD

**Issue by ThomasWaldmann** [dcwatson/deflate#11]
Hi Dan,

greetings from borgbackup development!

We currently discuss about getting rid of some code we have bundled and currently there is only crc32 code left.

We were searching where we could get some **fast** crc32 from and found `libdeflate` and your python wrapper for it.

Discussion: https://github.com/borgbackup/borg/issues/6316

Do you think a crc32 api could be added, so we could easily use it?

**Comment by ghost** [comment]
I've written a simple wrapper that should work as is unless there's something wrong with the function aesthetics (like no keywords, not that they're needed for a function as simple as crc32).
