### ISSUE TITLE
CI via github actions?

### ISSUE THREAD

**Issue by ThomasWaldmann** [dcwatson/deflate#16]
we could easily run the tests (see #15) via github actions, so that they are automatically executed for any commit / pull request.

would you like a PR for that?

**Comment by dcwatson** [comment]
Sure, that'd be great! Want to roll it in with #13 ?

**Comment by ThomasWaldmann** [comment]
will do a separate PR, #15 is ready for review / merging.

**Comment by dcwatson** [comment]
It seems like we're on the same page about the scope of this library, and you seem pretty motivated to make improvements. Would this be easier if I just gave you write access, or do you prefer working via PRs and issues? To be clear, I don't mind merging PRs and doing triage for this, so I'm not asking you to take on any real responsibility if you don't want it, just figured being able to work directly on the repo might be quicker/easier for you.

**Comment by ThomasWaldmann** [comment]
OK, that would be good! I'll be careful.

I usually work via PR and depending on their criticality leave them open for a while for review (if they are complex / difficult / critical) or merge them rather quickly (if they are trivial).
