### ISSUE TITLE
Add `libdeflate_zlib` bindings

### ISSUE THREAD

**Issue by kylebarron** [dcwatson/deflate#2]
`libdeflate` exposes both `libdeflate_gzip_compress` and `libdeflate_zlib_compress`, but you only currently wrap the gzip one. Any plans to also wrap the zlib one?

Is this as simple as replacing libdeflate_gzip_compress with libdeflate_zlib_compress? Would seem straightforward (if verbose) to copy the bindings again for zlib?

**Comment by dcwatson** [comment]
For compression, yes, it would be pretty trivial to just use libdeflate's zlib API in the same way the gzip API is currently used. But for decompression, you need to allocate a buffer for libdeflate to write into. Gzip has the benefit of including the original decompressed size as a check at the end of an archive, so I can know exactly how much memory to allocate. For other decompression APIs, you would need to guess and potentially loop, or expose an optional buffer_size to the Python call (or both). It was just much simpler to only do gzip to start.

I'm not opposed to expanding the library to include support for all of libdeflate's APIs, but don't really have the time or inclination to do the work myself. So long as the Python APIs can be dropped in for gzip/zlib `.compress(data)` and `.decompress(data)` with no options, I'll accept PRs.

**Comment by kylebarron** [comment]
Thanks, that's great to know and makes a lot of sense. I don't know C very well, so I doubt I'll take a stab in the near future.

**Comment by dcwatson** [comment]
I got a PR for adding raw DEFLATE support, so I went ahead and added zlib support too based on it. Better late than never?
